hotline_shouli="""SELECT
	F_REC_THREEDEPTNAME (
		"T_TASKINFO"."EXECUTEDEPTCODE",
		"T_TASKINFO"."DEPTCODE",
		"T_TASKINFO"."TASKID"
	) AS "THREE",
	COUNT (
		F_REC_THREEDEPTNAME (
			"T_TASKINFO"."EXECUTEDEPTCODE",
			"T_TASKINFO"."DEPTCODE",
			"T_TASKINFO"."TASKID"
		)
	) AS "SHOU_LI"
FROM
	"T_TASKINFO"
WHERE
	(
		percreatetime BETWEEN TO_DATE ( '%(start_time)s', 'yyyy-MM-dd HH24:mi:ss' ) 
		AND TO_DATE ( '%(end_time)s', 'yyyy-MM-dd HH24:mi:ss' ) 
		AND "T_TASKINFO"."INFOSOURCEID" IN (10, 68)
		AND (
			"T_TASKINFO"."DEPTCODE" = 20601
			OR  EXISTS (
				SELECT
					U0."ID"
				FROM
					"T_INFO_SOLVING" U0
				WHERE
					(
						U0."TASKID" = (T_TASKINFO."TASKID")
						AND (
							U0."EXECUTEDEPTCODE" = 20601
							OR U0."DEPTCODE" = 20601
						)
						AND U0."STATUS" != 3.0
					)
			) 
		)
	)
GROUP BY
	F_REC_THREEDEPTNAME (
		"T_TASKINFO"."EXECUTEDEPTCODE",
		"T_TASKINFO"."DEPTCODE",
		"T_TASKINFO"."TASKID"
	)

"""
hotline_shouli_old="""
SELECT
	F_REC_THREEDEPTNAME (
		"T_TASKINFO"."EXECUTEDEPTCODE",
		"T_TASKINFO"."DEPTCODE",
		"T_TASKINFO"."TASKID"
	) AS "THREE",
	COUNT (
		F_REC_THREEDEPTNAME (
			"T_TASKINFO"."EXECUTEDEPTCODE",
			"T_TASKINFO"."DEPTCODE",
			"T_TASKINFO"."TASKID"
		)
	) AS "SHOU_LI"
FROM
	"T_TASKINFO"
WHERE
	(
		discovertime BETWEEN TO_DATE ( '%(start_time)s', 'yyyy-MM-dd HH24:mi:ss' ) 
		AND TO_DATE ( '%(end_time)s', 'yyyy-MM-dd HH24:mi:ss' ) 
		AND "T_TASKINFO"."INFOSOURCEID" IN (10.0, 68.0)
		AND (
			"T_TASKINFO"."DEPTCODE" = 20601
			OR  EXISTS (
				SELECT
					U0."ID"
				FROM
					"T_INFO_SOLVING" U0
				WHERE
					(
						U0."TASKID" = (T_TASKINFO."TASKID")
						AND (
							U0."EXECUTEDEPTCODE" = 20601
							OR U0."DEPTCODE" = 20601
						)
						AND NOT (
							U0."STATUS" = 3.0
							AND U0."STATUS" IS NOT NULL
						)
					)
			) 
		)
	)
GROUP BY
	F_REC_THREEDEPTNAME (
		"T_TASKINFO"."EXECUTEDEPTCODE",
		"T_TASKINFO"."DEPTCODE",
		"T_TASKINFO"."TASKID"
	)
"""
hotline_2="""
SELECT
	F_REC_THREEDEPTNAME (
		"T_TASKINFO"."EXECUTEDEPTCODE",
		"T_TASKINFO"."DEPTCODE",
		"T_TASKINFO"."TASKID"
	) AS "THREE",
	COUNT (
		F_REC_THREEDEPTNAME (
			"T_TASKINFO"."EXECUTEDEPTCODE",
			"T_TASKINFO"."DEPTCODE",
			"T_TASKINFO"."TASKID"
		)
	) AS "SOU_COUNT",
	SUM (
		CASE
		WHEN "T_TASKINFO"."ISFIRSTCONTACT" = 1.0 THEN
			1
		ELSE
			0
		END
	) AS "FIRST_YES",
	SUM (
		CASE
		WHEN "T_TASKINFO"."ISFIRSTCONTACT" = 0.0 THEN
			1
		ELSE
			0
		END
	) AS "FIRST_NO",
	(
		SUM (
			CASE
			WHEN "T_TASKINFO"."ISFIRSTCONTACT" = 1.0 THEN
				1
			ELSE
				0
			END
		) + SUM (
			CASE
			WHEN "T_TASKINFO"."ISFIRSTCONTACT" = 0.0 THEN
				1
			ELSE
				0
			END
		)
	) AS "FIRST_TOTAL",
	CASE
WHEN (
	SUM (
		CASE
		WHEN "T_TASKINFO"."ISFIRSTCONTACT" = 1.0 THEN
			1
		ELSE
			0
		END
	) + SUM (
		CASE
		WHEN "T_TASKINFO"."ISFIRSTCONTACT" = 0.0 THEN
			1
		ELSE
			0
		END
	)
) = 0 THEN
	1
ELSE
	(
		SUM (
			CASE
			WHEN "T_TASKINFO"."ISFIRSTCONTACT" = 1.0 THEN
				1
			ELSE
				0
			END
		) / (
			SUM (
				CASE
				WHEN "T_TASKINFO"."ISFIRSTCONTACT" = 1.0 THEN
					1
				ELSE
					0
				END
			) + SUM (
				CASE
				WHEN "T_TASKINFO"."ISFIRSTCONTACT" = 0.0 THEN
					1
				ELSE
					0
				END
			)
		)
	)
END AS "FIRST_RATIO",
 SUM (
	CASE
	WHEN "T_TASKINFO"."CASEVALUATIONNAME" = '实际解决' THEN
		1
	ELSE
		0
	END
) AS "REAL_SOLVE",
 SUM (
	CASE
	WHEN "T_TASKINFO"."CASEVALUATIONNAME" = '解释说明' THEN
		1
	ELSE
		0
	END
) AS "JIE_SOLVE",
 (
	SUM (
		CASE
		WHEN "T_TASKINFO"."CASEVALUATIONNAME" = '实际解决' THEN
			1
		ELSE
			0
		END
	) + SUM (
		CASE
		WHEN "T_TASKINFO"."CASEVALUATIONNAME" = '解释说明' THEN
			1
		ELSE
			0
		END
	)
) AS "TOTAL_SOLVE",
 CASE
WHEN (
	SUM (
		CASE
		WHEN "T_TASKINFO"."CASEVALUATIONNAME" = '实际解决' THEN
			1
		ELSE
			0
		END
	) + SUM (
		CASE
		WHEN "T_TASKINFO"."CASEVALUATIONNAME" = '解释说明' THEN
			1
		ELSE
			0
		END
	)
) = 0 THEN
	0
ELSE
	(
		SUM (
			CASE
			WHEN "T_TASKINFO"."CASEVALUATIONNAME" = '实际解决' THEN
				1
			ELSE
				0
			END
		) / (
			SUM (
				CASE
				WHEN "T_TASKINFO"."CASEVALUATIONNAME" = '实际解决' THEN
					1
				ELSE
					0
				END
			) + SUM (
				CASE
				WHEN "T_TASKINFO"."CASEVALUATIONNAME" = '解释说明' THEN
					1
				ELSE
					0
				END
			)
		)
	)
END AS "REAL_SOLVE_RATIO",
 CASE
WHEN (
	SUM (
		CASE
		WHEN "T_TASKINFO"."CASEVALUATIONNAME" = '实际解决' THEN
			1
		ELSE
			0
		END
	) + SUM (
		CASE
		WHEN "T_TASKINFO"."CASEVALUATIONNAME" = '解释说明' THEN
			1
		ELSE
			0
		END
	)
) = 0 THEN
	0
ELSE
	(
		SUM (
			CASE
			WHEN "T_TASKINFO"."CASEVALUATIONNAME" = '解释说明' THEN
				1
			ELSE
				0
			END
		) / (
			SUM (
				CASE
				WHEN "T_TASKINFO"."CASEVALUATIONNAME" = '实际解决' THEN
					1
				ELSE
					0
				END
			) + SUM (
				CASE
				WHEN "T_TASKINFO"."CASEVALUATIONNAME" = '解释说明' THEN
					1
				ELSE
					0
				END
			)
		)
	)
END AS "JIE_SOLVE_RATIO",
 SUM (
	CASE
	WHEN "T_TASKINFO"."ALLMANYINAME_BF" = '满意' THEN
		1
	WHEN "T_TASKINFO"."ALLMANYINAME_BF" = '基本满意' THEN
		0.8
	WHEN "T_TASKINFO"."ALLMANYINAME_BF" = '一般' THEN
		0.6
	ELSE
		0
	END
) AS "MAN_YI",
 SUM (
	CASE
	WHEN "T_TASKINFO"."ALLMANYINAME_BF" IN (
		'满意',
		'不满意',
		'基本满意',
		'一般'
	) THEN
		1
	ELSE
		0
	END
) AS "MAN_YI_TOTAL",
 CASE
WHEN SUM (
	CASE
	WHEN "T_TASKINFO"."ALLMANYINAME_BF" IN (
		'满意',
		'不满意',
		'基本满意',
		'一般'
	) THEN
		1
	ELSE
		0
	END
) = 0 THEN
	0
ELSE
	(
		SUM (
			CASE
			WHEN "T_TASKINFO"."ALLMANYINAME_BF" = '满意' THEN
				1
			WHEN "T_TASKINFO"."ALLMANYINAME_BF" = '基本满意' THEN
				0.8
			WHEN "T_TASKINFO"."ALLMANYINAME_BF" = '一般' THEN
				0.6
			ELSE
				0
			END
		) / SUM (
			CASE
			WHEN "T_TASKINFO"."ALLMANYINAME_BF" IN (
				'满意',
				'不满意',
				'基本满意',
				'一般'
			) THEN
				1
			ELSE
				0
			END
		)
	)
END AS "MAN_YI_RATIO"
FROM
	"T_TASKINFO"
WHERE
	(
	"T_TASKINFO"."ENDTIME" BETWEEN TO_DATE ( '2018-06-01 00:00:00', 'yyyy-MM-dd HH24:mi:ss' ) 
		AND TO_DATE ( '2018-06-30 23:59:59', 'yyyy-MM-dd HH24:mi:ss' ) 
		AND "T_TASKINFO"."INFOSOURCEID" IN (10, 68)
		AND (
			"T_TASKINFO"."DEPTCODE" = 20601
			OR  EXISTS (
				SELECT
					U0."ID"
				FROM
					"T_INFO_SOLVING" U0
				WHERE
					(
						U0."TASKID" = (T_TASKINFO."TASKID")
						AND (
							U0."EXECUTEDEPTCODE" = 20601
							OR U0."DEPTCODE" = 20601
						)
						AND NOT (
							U0."STATUS" = 3.0
							AND U0."STATUS" IS NOT NULL
						)
					)
			) 
		)
	)
GROUP BY
	F_REC_THREEDEPTNAME (
		"T_TASKINFO"."EXECUTEDEPTCODE",
		"T_TASKINFO"."DEPTCODE",
		"T_TASKINFO"."TASKID"
	)
"""

hotline_2_you="""
SELECT
	F_REC_THREEDEPTNAME (
		"T_TASKINFO"."EXECUTEDEPTCODE",
		"T_TASKINFO"."DEPTCODE",
		"T_TASKINFO"."TASKID"
	) AS "THREE",
	COUNT (
		F_REC_THREEDEPTNAME (
			"T_TASKINFO"."EXECUTEDEPTCODE",
			"T_TASKINFO"."DEPTCODE",
			"T_TASKINFO"."TASKID"
		)
	) AS "SOU_COUNT",
	SUM (
		CASE
		WHEN "T_TASKINFO"."ISFIRSTCONTACT" = 1.0 THEN
			1
		ELSE
			0
		END
	) AS "FIRST_YES",
	SUM (
		CASE
		WHEN "T_TASKINFO"."ISFIRSTCONTACT" = 0.0 THEN
			1
		ELSE
			0
		END
	) AS "FIRST_NO",

 SUM (
	CASE
	WHEN "T_TASKINFO"."CASEVALUATIONNAME" = '实际解决' THEN
		1
	ELSE
		0
	END
) AS "REAL_SOLVE",
 SUM (
	CASE
	WHEN "T_TASKINFO"."CASEVALUATIONNAME" = '解释说明' THEN
		1
	ELSE
		0
	END
) AS "JIE_SOLVE",
 

 SUM (
	CASE
	WHEN "T_TASKINFO"."ALLMANYINAME_BF" = '满意' THEN
		1
	WHEN "T_TASKINFO"."ALLMANYINAME_BF" = '基本满意' THEN
		0.8
	WHEN "T_TASKINFO"."ALLMANYINAME_BF" = '一般' THEN
		0.6
	ELSE
		0
	END
) AS "MAN_YI",
 SUM (
	CASE
	WHEN "T_TASKINFO"."ALLMANYINAME_BF" IN (
		'满意',
		'不满意',
		'基本满意',
		'一般'
	) THEN
		1
	ELSE
		0
	END
) AS "MAN_YI_TOTAL"

FROM
	"T_TASKINFO"
WHERE
	(
	"T_TASKINFO"."ENDTIME" BETWEEN TO_DATE ( '%(start_time)s', 'yyyy-MM-dd HH24:mi:ss' ) 
		AND TO_DATE ( '%(end_time)s', 'yyyy-MM-dd HH24:mi:ss' ) 
		AND "T_TASKINFO"."INFOSOURCEID" IN (10, 68)
		AND (
			"T_TASKINFO"."DEPTCODE" = 20601
			OR  EXISTS (
				SELECT
					U0."ID"
				FROM
					"T_INFO_SOLVING" U0
				WHERE
					(
						U0."TASKID" = (T_TASKINFO."TASKID")
						AND (
							U0."EXECUTEDEPTCODE" = 20601
							OR U0."DEPTCODE" = 20601
						)
						 AND U0."STATUS" != 3
					)
			) 
		)
	)
GROUP BY
	F_REC_THREEDEPTNAME (
		"T_TASKINFO"."EXECUTEDEPTCODE",
		"T_TASKINFO"."DEPTCODE",
		"T_TASKINFO"."TASKID"
	)
"""

grid_a1_old="""SELECT
	F_REC_THREEDEPTNAME ( "T_TASKINFO"."EXECUTEDEPTCODE", "T_TASKINFO"."DEPTCODE", "T_TASKINFO"."TASKID" ) AS "THREE",
	COUNT( 1 ) AS "COUNT_ALL",
	SUM( CASE WHEN "T_TASKINFO"."INFOTYPENAME" = '部件' THEN 1 ELSE 0 END ) AS "COUNT_BU",
	SUM( CASE WHEN "T_TASKINFO"."INFOTYPENAME" = '事件' THEN 1 ELSE 0 END ) AS "COUNT_SHI" 
FROM
	"T_TASKINFO" 
WHERE
	(
	"T_TASKINFO"."DISCOVERTIME" BETWEEN TO_DATE ( '%(start_time)s', 'yyyy-MM-dd HH24:mi:ss' ) 
		AND TO_DATE ( '%(end_time)s', 'yyyy-MM-dd HH24:mi:ss' ) 
	AND "T_TASKINFO"."STREETCODE" = 1806 
	AND "T_TASKINFO"."INFOSOURCEID" = 1
	AND "T_TASKINFO"."STATUS" IN ( 3, 4, 5, 6, 7, 8, 9, 100 ) 
AND EXISTS (
SELECT
U0."ID" 
FROM
"T_INFO_SOLVING" U0 
WHERE
(
U0."TASKID" = ( T_TASKINFO."TASKID" ) 
	AND ( U0."EXECUTEDEPTCODE" = 20601 OR U0."DEPTCODE" = 20601 ) 
	AND NOT ( U0."STATUS" = 3 AND U0."STATUS" IS NOT NULL ))) 
	) 
GROUP BY
F_REC_THREEDEPTNAME ( "T_TASKINFO"."EXECUTEDEPTCODE", "T_TASKINFO"."DEPTCODE", "T_TASKINFO"."TASKID" )"""

grid_a1="""SELECT
	F_REC_THREEDEPTNAME ( "T_INFO_MAIN"."EXECUTEDEPTCODE", "T_INFO_MAIN"."DEPTCODE", "T_INFO_MAIN"."TASKID" ) AS "THREE",
	COUNT( 1 ) AS "COUNT_ALL",
	-- 	部件
	SUM( CASE WHEN "T_INFO_MAIN"."INFOTYPEID" = 0 THEN 1 ELSE 0 END ) AS "COUNT_BU",
-- 	事件
	SUM( CASE WHEN "T_INFO_MAIN"."INFOTYPEID" = 1 THEN 1 ELSE 0 END ) AS "COUNT_SHI" 

FROM
	"T_INFO_MAIN"
WHERE
	(
	"T_INFO_MAIN"."DISCOVERTIME" BETWEEN TO_DATE( '%(start_time)s', 'yyyy-MM-dd HH24:mi:ss' ) 
	AND TO_DATE( '%(end_time)s', 'yyyy-MM-dd HH24:mi:ss' ) 
	AND "T_INFO_MAIN"."STREETCODE" = 1806 
	AND "T_INFO_MAIN"."INFOSOURCEID" = 1 
	AND "T_INFO_MAIN"."STATUS" IN ( 3, 4, 5, 6, 7, 8, 9, 100 ) 
	AND (
	EXISTS (
SELECT
	1 
FROM
	"T_INFO_SOLVING" U0 
WHERE
	(
	U0."TASKID" =  "T_INFO_MAIN"."TASKID" 
	AND ( U0."EXECUTEDEPTCODE" = '20601' OR U0."DEPTCODE" = '20601' ) 
-- 	AND NOT ( U0."STATUS" = 3 AND U0."STATUS" IS NOT NULL )
	)
	) 
	OR "T_INFO_MAIN"."DEPTCODE" = '20601' 
	)
	)
GROUP BY
	F_REC_THREEDEPTNAME (
	"T_INFO_MAIN"."EXECUTEDEPTCODE",
	"T_INFO_MAIN"."DEPTCODE",
	"T_INFO_MAIN"."TASKID"
	)
"""

grid_a2="""SELECT
	F_REC_THREEDEPTNAME ( "T_INFO_MAIN"."EXECUTEDEPTCODE", "T_INFO_MAIN"."DEPTCODE", "T_INFO_MAIN"."TASKID" ) AS "THREE",
	COUNT( 1 ) AS "COUNT_CUN" 
FROM
	"T_INFO_MAIN" 
WHERE
	(
	"T_INFO_MAIN"."DISCOVERTIME" BETWEEN TO_DATE ( '%(start_time)s', 'yyyy-MM-dd HH24:mi:ss' ) 
		AND TO_DATE ( '%(end_time)s', 'yyyy-MM-dd HH24:mi:ss' ) 
	AND "T_INFO_MAIN"."STREETCODE" = 1806 
	AND "T_INFO_MAIN"."STATUS" IN ( 3, 4, 5, 6, 7, 8, 9, 100 ) 
AND( EXISTS (
SELECT
U0."ID" 
FROM
"T_INFO_SOLVING" U0 
WHERE
(
U0."TASKID" = ( T_INFO_MAIN."TASKID" ) 
	AND ( U0."EXECUTEDEPTCODE" = '20601' OR U0."DEPTCODE" = 20601 ) 
-- 	AND NOT ( U0."STATUS" = 3 AND U0."STATUS" IS NOT NULL )
	)) 
	OR T_INFO_MAIN.DEPTCODE = '20601' 
	)
	AND "T_INFO_MAIN"."INFOSOURCEID" = 36
	) 
GROUP BY
F_REC_THREEDEPTNAME ( "T_INFO_MAIN"."EXECUTEDEPTCODE", "T_INFO_MAIN"."DEPTCODE", "T_INFO_MAIN"."TASKID" )
"""

grid_a2_old="""SELECT
	F_REC_THREEDEPTNAME ( "T_TASKINFO"."EXECUTEDEPTCODE", "T_TASKINFO"."DEPTCODE", "T_TASKINFO"."TASKID" ) AS "THREE",
	COUNT( 1 ) AS "COUNT_CUN" 
FROM
	"T_TASKINFO" 
WHERE
	(
	"T_TASKINFO"."DISCOVERTIME" BETWEEN TO_DATE ( '%(start_time)s', 'yyyy-MM-dd HH24:mi:ss' ) 
		AND TO_DATE ( '%(end_time)s', 'yyyy-MM-dd HH24:mi:ss' ) 
	AND "T_TASKINFO"."STREETCODE" = 1806 
	AND "T_TASKINFO"."STATUS" IN ( 3, 4, 5, 6, 7, 8, 9, 100 ) 
AND EXISTS (
SELECT
U0."ID" 
FROM
"T_INFO_SOLVING" U0 
WHERE
(
U0."TASKID" = ( T_TASKINFO."TASKID" ) 
	AND ( U0."EXECUTEDEPTCODE" = '20601' OR U0."DEPTCODE" = 20601 ) 
	AND NOT ( U0."STATUS" = 3 AND U0."STATUS" IS NOT NULL )))
	AND "T_TASKINFO"."INFOSOURCEID" = 36
	) 
GROUP BY
F_REC_THREEDEPTNAME ( "T_TASKINFO"."EXECUTEDEPTCODE", "T_TASKINFO"."DEPTCODE", "T_TASKINFO"."TASKID" )"""


gird_a3="""
SELECT
	REPORTER,
	COUNT( 1 ) AS "COUNT_WEI" 

FROM
	CITYGRID.T_TASKINFO main 
WHERE
	1 = 1 
	AND discovertime BETWEEN TO_DATE( '%(start_time)s', 'yyyy-MM-dd HH24:mi:ss' ) 
	AND TO_DATE( '%(end_time)s', 'yyyy-MM-dd HH24:mi:ss' ) 
	AND InfoSourceid IN ( 61 ) 
	AND STREETCODE IN ( '1806' ) 
GROUP BY
REPORTER
"""

grid_a3_almost_right="""SELECT
	"T_INFO_MAIN"."REPORTER",
	COUNT( 1 ) AS "COUNT_WEI" 
FROM
	"T_INFO_MAIN" 
WHERE
	(
		"T_INFO_MAIN"."DISCOVERTIME" BETWEEN TO_DATE ( '%(start_time)s', 'yyyy-MM-dd HH24:mi:ss' ) 
		AND TO_DATE ( '%(end_time)s', 'yyyy-MM-dd HH24:mi:ss' ) 
	AND "T_INFO_MAIN"."STREETCODE" = 1806 
	AND "T_INFO_MAIN"."STATUS" IN ( 3, 4, 5, 6, 7, 8, 9, 100 ) 
AND (EXISTS (
SELECT
U0."ID" 
FROM
"T_INFO_SOLVING" U0 
WHERE
(
U0."TASKID" = ( T_INFO_MAIN."TASKID" ) 
	AND ( U0."EXECUTEDEPTCODE" = '20601' OR U0."DEPTCODE" = 20601 ) 
-- 	AND NOT ( U0."STATUS" = 3 AND U0."STATUS" IS NOT NULL )
	))
	OR T_INFO_MAIN.DEPTCODE = '20601' 
	)
	AND "T_INFO_MAIN"."INFOSOURCEID" = 61 
	) 
GROUP BY
"T_INFO_MAIN"."REPORTER"
"""

grid_a3_old="""SELECT
	"T_TASKINFO"."REPORTER",
	COUNT( 1 ) AS "COUNT_WEI" 
FROM
	"T_TASKINFO" 
WHERE
	(
		"T_TASKINFO"."DISCOVERTIME" BETWEEN TO_DATE ( '%(start_time)s', 'yyyy-MM-dd HH24:mi:ss' ) 
		AND TO_DATE ( '%(end_time)s', 'yyyy-MM-dd HH24:mi:ss' ) 
	AND "T_TASKINFO"."STREETCODE" = 1806 
	AND "T_TASKINFO"."STATUS" IN ( 3, 4, 5, 6, 7, 8, 9, 100 ) 
AND EXISTS (
SELECT
U0."ID" 
FROM
"T_INFO_SOLVING" U0 
WHERE
(
U0."TASKID" = ( T_TASKINFO."TASKID" ) 
	AND ( U0."EXECUTEDEPTCODE" = '20601' OR U0."DEPTCODE" = 20601 ) 
	AND NOT ( U0."STATUS" = 3 AND U0."STATUS" IS NOT NULL )))
	AND "T_TASKINFO"."INFOSOURCEID" = 61 
	AND F_REC_THREEDEPTNAME ( "T_TASKINFO"."EXECUTEDEPTCODE", "T_TASKINFO"."DEPTCODE", "T_TASKINFO"."TASKID" ) IS NULL 
	) 
GROUP BY
"T_TASKINFO"."REPORTER"
"""
grid_4="""
SELECT
	UPKEEPERNAME AS KEEPERNAME,
	COUNT( 1 ) AS COUNT_KEEPER

FROM
	CITYGRID.T_TASKINFO main 
WHERE
	1 = 1 
	AND discovertime BETWEEN TO_DATE( '%(start_time)s', 'yyyy-MM-dd HH24:mi:ss' ) 
	AND TO_DATE( '%(end_time)s', 'yyyy-MM-dd HH24:mi:ss' ) 
	AND InfoSourceid IN ( 1 ) 
	AND STREETCODE IN ( '1806' ) 

	GROUP BY
	UPKEEPERNAME
"""
grid_a4_almost_right="""
SELECT
	F_KEEPERNAME_BYKEEPERSN ( T_INFO_MAIN.KeeperSN ) AS "KEEPERNAME",
	COUNT( 1 ) AS "COUNT_KEEPER" 
FROM
	"T_INFO_MAIN" 
WHERE
	(
		"T_INFO_MAIN"."DISCOVERTIME" BETWEEN TO_DATE ( '%(start_time)s', 'yyyy-MM-dd HH24:mi:ss' ) 
		AND TO_DATE ( '%(end_time)s', 'yyyy-MM-dd HH24:mi:ss' ) 
	AND "T_INFO_MAIN"."STREETCODE" = 1806 
	AND "T_INFO_MAIN"."STATUS" IN ( 3, 4, 5, 6, 7, 8, 9, 100 )
--          AND F_KEEPERNAME_BYKEEPERSN ( T_INFO_MAIN.KeeperSN ) IN ('张永泉', '徐洁'，'俞凤雷', '汪建军'，'周明', '徐卫东'，'张彩军', '许雅俊'，'范超群', '王坚'，'王陈佳', '瞿翠荣'，'姜嗣杰', '杨豪杰'，'崔文峰', '陈涛'，'张建峰', '唐晨'，'万亮', '毛建林'，'毛伟强', '陈建华', '王伟')
    
	
AND (EXISTS (
SELECT
	U0."ID" 
FROM
	"T_INFO_SOLVING" U0 
WHERE
	(
	U0."TASKID" = ( T_INFO_MAIN."TASKID" ) 
 	AND ( U0."EXECUTEDEPTCODE" = '20601' OR U0."DEPTCODE" = 20601 ) 
-- 	AND NOT ( U0."STATUS" = 3 AND U0."STATUS" IS NOT NULL )
	)) 
	OR T_INFO_MAIN.DEPTCODE = '20601' 
	)
	
	AND "T_INFO_MAIN"."INFOSOURCEID" =1
	) 
GROUP BY
	F_KEEPERNAME_BYKEEPERSN ( T_INFO_MAIN.KeeperSN )"""

grid_a4_old="""
SELECT
	"T_TASKINFO"."UPKEEPERNAME",
	COUNT( 1 ) AS "COUNT_KEEPER" 
FROM
	"T_TASKINFO" 
WHERE
	(
		"T_TASKINFO"."DISCOVERTIME" BETWEEN TO_DATE ( '%(start_time)s', 'yyyy-MM-dd HH24:mi:ss' ) 
		AND TO_DATE ( '%(end_time)s', 'yyyy-MM-dd HH24:mi:ss' ) 
	AND "T_TASKINFO"."STREETCODE" = 1806 
	AND "T_TASKINFO"."STATUS" IN ( 3, 4, 5, 6, 7, 8, 9, 100 )
        AND "T_TASKINFO"."UPKEEPERNAME" IN ('张永泉', '徐洁'，'俞凤雷', '汪建军'，'周明', '徐卫东'，'张彩军', '许雅俊'，'范超群', '王坚'，'王陈佳', '瞿翠荣'，'姜嗣杰', '杨豪杰'，'崔文峰', '陈涛'，'张建峰', '唐晨'，'万亮', '毛建林'，'毛伟强', '陈建华', '王伟')
    
	
AND EXISTS (
SELECT
	U0."ID" 
FROM
	"T_INFO_SOLVING" U0 
WHERE
	(
	U0."TASKID" = ( T_TASKINFO."TASKID" ) 
 	AND ( U0."EXECUTEDEPTCODE" = '20601' OR U0."DEPTCODE" = 20601 ) 
	AND NOT ( U0."STATUS" = 3 AND U0."STATUS" IS NOT NULL ))) 
	
	AND "T_TASKINFO"."INFOSOURCEID" = 1
	) 
GROUP BY
	"T_TASKINFO"."UPKEEPERNAME"
"""

